[phases.setup]
nixPkgs = []

[phases.build]
cmds = ["echo 'Using Dockerfile in BloodPressureMonitor.API'"]

[start]
cmd = "echo 'This project uses Docker - check BloodPressureMonitor.API/Dockerfile'"
